import path from "path";
import fs from "fs";

import HtmlWebpackPlugin from "html-webpack-plugin";

import { NODE_ENV, PACKAGE, GIT_INFO } from "../config";

const minifyOptions = {
  caseSensitive: false,
  collapseBooleanAttributes: true,
  collapseInlineTagWhitespace: false,
  collapseWhitespace: true,
  conservativeCollapse: false,
  customAttrAssign: [],
  customAttrCollapse: /ng-class/,
  customAttrSurround: [],
  customEventAttributes: [/^on[a-z]{3,}$/],
  decodeEntities: true,
  html5: true,
  ignoreCustomComments: [/^!/],
  ignoreCustomFragments: [/<%[\s\S]*?%>/, /<\?[\s\S]*?\?>/],
  includeAutoGeneratedTags: false,
  keepClosingSlash: false,
  maxLineLength: 0,
  minifyCSS: true,
  minifyJS: true,
  preserveLineBreaks: false,
  preventAttributesEscaping: false,
  processConditionalComments: true,
  processScripts: ["text/html"],
  quoteCharacter: '"',
  removeAttributeQuotes: true,
  removeComments: true,
  removeEmptyAttributes: true,
  removeEmptyElements: false,
  removeOptionalTags: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  removeTagWhitespace: true,
  sortAttributes: true,
  sortClassName: true,
  trimCustomFragments: true,
  useShortDoctype: true
};

const htmlIndex = new HtmlWebpackPlugin({
  inject: true,
  filename: "index.html",
  template: "templates/index.html",
  title: PACKAGE.config.title,
  description: PACKAGE.description,
  og: {
    title: PACKAGE.config.title,
    type: "website",
    image: `${PACKAGE.homepage}/share.jpg`,
    url: PACKAGE.homepage,
    description: PACKAGE.description
  },
  twitter: {
    imageAlt: PACKAGE.description,
    handle: PACKAGE.config.handle
  },
  analyticsUA: PACKAGE.config.analyticsUA,
  gitInfo: GIT_INFO,
  NODE_ENV: NODE_ENV,
  minify: NODE_ENV === "development" ? false : minifyOptions
});

export { htmlIndex };
